apiVersion: apps/v1
kind: Deployment
metadata:
  name: t-manager-module 
spec:
  selector: 
    matchLabels:
      appname: module-webapp
  replicas: 2
  template: 
    metadata:
      labels:
        appname: module-webapp
    spec:
      containers:
      - name: module-image
        image: tmanager-module:latest
        imagePullPolicy: "Never"
        ports:
            - containerPort: 8002

---
kind: Service
apiVersion: v1
metadata:
  name: tmanager-module-webapp
spec:
  selector:
    appname: module-webapp
  ports:
    - name: http
      port: 8002

#kubectl port-forward deployment/t-manager-module 8002:8002