spring:
  application:
    name: module
  profiles:
    active: ${spring.profiles.active}
     
server:
  servlet:
    context-path: /module
  port: 8002
  
module:
  oauth:
    server:
       port: 8001
       path: auth-service
       address: http://localhost
    clientId: app-open-source
    clientSecret: password-open-source   
    
management:
  endpoints:
    web:
      exposure:
        include: "*" 
