module:
  oauth:
    clientRedirectUrl: https://18.194.82.207:8002/module/init
    
spring:
  data:
    mongodb:
      authentication-database: admin
      username: t-manager-module-user
      password: t-manager-module-password
      host: 18.194.82.207
      port: 27017
      database: t-manager-module

server:
  ssl:
    key-store-type: pkcs12
    key-store: classpath:keystore/t-manager.p12
    key-store-password: t-manager
    key-alias: t-manager