spring:
  application:
    name: module
  profiles:
    active: ${spring.profiles.active}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration, org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
     
server:
  servlet:
    context-path: /module
  port: 8002

trust:
  store: 
    classpath: classpath:keystore/t-manager.p12
    password: t-manager
    
module:
  oauth:
    server:
       port: 8001
       path: auth-service
       address: https://18.194.82.207
    clientId: app-open-source
    clientSecret: password-open-source   
  timeoutValue: 5000
  threadPool: 10
  external:
    bar:
      url: https://18.194.82.207:8003/bar
  deploy:
    tech: in-memory
    external-communication-tech: rest

management:
  endpoints:
    web:
      exposure:
        include: "*" 
