spring:
  application:
    name: module
  profiles:
    default: local-in-memory
    active: local-in-memory
     
server:
  servlet:
    context-path: /module
  port: 8002
  
logging:
  path: logs
  
module:
  oauth:
    server:
       port: 8001
       path: auth-service
       #address: http://3.121.59.80
       address: http://localhost
    clientId: app-open-source
    clientSecret: password-open-source   
    clientRedirectUrl: http://localhost:8080/module/init
    
management:
  endpoints:
    web:
      exposure:
        include: "*" 
